DEFAULT_QUESTIONS = [
    # NEGOCIO
    ("Negocio", "¿Cuál es el objetivo principal del sistema o producto a desarrollar?", "Abierta", True),
    ("Negocio", "¿Quiénes son los usuarios finales del sistema?", "Abierta", True),
    ("Negocio", "¿Qué problema concreto busca resolver esta solución?", "Abierta", True),
    ("Negocio", "¿Existen sistemas actuales que realicen funciones similares?", "Cerrada", True),
    ("Negocio", "¿Qué valor diferencial debe aportar este sistema respecto a la situación actual?", "Abierta", True),
    ("Negocio", "¿Cuáles son las reglas de negocio más importantes que el sistema debe respetar?", "Abierta", True),
    ("Negocio", "¿Quiénes son los principales stakeholders del proyecto?", "Abierta", True),
    ("Negocio", "¿Cómo se mide el éxito del proceso que se va a automatizar o mejorar?", "Abierta", True),
    ("Negocio", "¿Hay alguna normativa legal o regulación del sector que el sistema deba cumplir?", "Cerrada", True),
    ("Negocio", "¿Cuáles son los riesgos de negocio más preocupantes para el cliente?", "Abierta", True),
    ("Negocio", "¿El sistema reemplaza un proceso manual o un sistema anterior?", "Cerrada", True),

    # FUNCIONAL
    ("Funcional", "¿Qué funcionalidades considera indispensables para la primera versión?", "Abierta", True),
    ("Funcional", "¿El sistema debe gestionar usuarios con distintos roles o permisos?", "Cerrada", True),
    ("Funcional", "¿Qué reportes o consultas necesita generar el sistema?", "Abierta", True),
    ("Funcional", "¿El sistema requiere flujos de aprobación o notificaciones automáticas?", "Cerrada", True),
    ("Funcional", "¿Qué acciones puede realizar cada tipo de usuario dentro del sistema?", "Abierta", True),
    ("Funcional", "¿El sistema necesita gestionar archivos o documentos adjuntos?", "Cerrada", True),
    ("Funcional", "¿Debe haber un módulo de búsqueda o filtrado avanzado de datos?", "Cerrada", True),
    ("Funcional", "¿El sistema debe enviar correos electrónicos o notificaciones push?", "Selección múltiple", True),
    ("Funcional", "¿Se requiere un historial o auditoría de cambios realizados en el sistema?", "Cerrada", True),
    ("Funcional", "¿Qué datos maestros necesita gestionar el sistema (catálogos, configuraciones)?", "Abierta", True),
    ("Funcional", "¿El sistema necesita importar o exportar datos en algún formato específico?", "Cerrada", True),

    # NO FUNCIONAL
    ("No funcional", "¿Cuántos usuarios simultáneos se esperan en producción?", "Abierta", True),
    ("No funcional", "¿Hay requerimientos de disponibilidad (SLA, horarios de operación)?", "Abierta", True),
    ("No funcional", "¿Existen normas de seguridad o privacidad de datos que deban cumplirse?", "Abierta", True),
    ("No funcional", "¿Cuál es el tiempo de respuesta máximo aceptable para las operaciones críticas?", "Abierta", True),
    ("No funcional", "¿Qué nivel de escalabilidad se espera del sistema a futuro?", "Abierta", True),
    ("No funcional", "¿El sistema debe ser accesible para personas con discapacidad (WCAG)?", "Cerrada", True),
    ("No funcional", "¿Cuáles son los requisitos de backup y recuperación ante desastres?", "Abierta", True),
    ("No funcional", "¿Hay requerimientos de rendimiento para consultas o reportes pesados?", "Cerrada", True),
    ("No funcional", "¿El sistema necesita soporte multilenguaje o multi-moneda?", "Selección múltiple", True),
    ("No funcional", "¿Qué nivel de logging o monitoreo se requiere en producción?", "Abierta", True),
    ("No funcional", "¿Se requiere auditoría de acceso y acciones de usuarios en el sistema?", "Cerrada", True),

    # RESTRICCION
    ("Restricción", "¿Cuál es el presupuesto estimado disponible para el proyecto?", "Abierta", True),
    ("Restricción", "¿Existe una fecha límite de entrega definida?", "Cerrada", True),
    ("Restricción", "¿Hay tecnologías o plataformas obligatorias a utilizar?", "Abierta", True),
    ("Restricción", "¿El equipo de desarrollo tiene restricciones de tamaño o disponibilidad?", "Abierta", True),
    ("Restricción", "¿Existen restricciones de infraestructura actual (servidores, cloud)?", "Abierta", True),
    ("Restricción", "¿El sistema debe funcionar en ambientes offline o con conectividad limitada?", "Cerrada", True),
    ("Restricción", "¿Hay restricciones sobre manejo de datos personales (GDPR, Ley de datos)?", "Cerrada", True),
    ("Restricción", "¿Se requiere compatibilidad con versiones específicas de software o hardware?", "Abierta", True),
    ("Restricción", "¿Existen procesos de aprobación internos que puedan afectar los plazos?", "Cerrada", True),
    ("Restricción", "¿Hay dependencias con terceros que puedan generar retrasos?", "Abierta", True),

    # INTERFAZ
    ("Interfaz", "¿El sistema debe integrarse con otros sistemas externos o APIs?", "Cerrada", True),
    ("Interfaz", "¿Qué dispositivos usarán los usuarios (PC, tablet, móvil)?", "Selección múltiple", True),
    ("Interfaz", "¿El cliente tiene guías de identidad visual o branding a respetar?", "Cerrada", True),
    ("Interfaz", "¿Hay algún ERP, CRM o base de datos existente con la que deba integrarse?", "Cerrada", True),
    ("Interfaz", "¿El sistema debe exponer una API para que terceros consuman sus datos?", "Cerrada", True),
    ("Interfaz", "¿Qué tipo de autenticación se requiere (usuario/contraseña, SSO, OAuth)?", "Selección múltiple", True),
    ("Interfaz", "¿Cómo se espera que sea la curva de aprendizaje de los usuarios finales?", "Abierta", True),
    ("Interfaz", "¿El sistema debe usar algún protocolo específico (REST, SOAP, WebSocket)?", "Abierta", True),
    ("Interfaz", "¿Hay requisitos de impresión o generación de reportes en PDF u otros formatos?", "Cerrada", True),
    ("Interfaz", "¿Los usuarios requieren dashboard con métricas o indicadores visuales?", "Cerrada", True),
    ("Interfaz", "¿Existe algún servicio de pagos u otros servicios cloud que deban integrarse?", "Cerrada", True),
]
